name: golangci-lint
on:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: lint electrumx package
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          working-directory: electrumx

      - name: lint examples 
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          working-directory: examples

